AllCops:
  NewCops: enable
  Include:
    - foo.unusual_extension
    - <**/*.rb<
    - <**/*.gemfile<
    - <**/*.gemspec<
    - <**/*.rake<
    - <**/*.ru<
    - <**/Gemfile<
    - <**/Rakefile<

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Encoding:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/LineLength:
  Max: 200
